In [166]:
from scipy import stats
import plotly.express as px
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [178]:
df=pd.read_csv("/content/logatta.csv")
df.head()

Age     BusinessTravel  Education MaritalStatus OverTime  EmployeeNumber  \
0   41      Travel_Rarely          2        Single      Yes               1   
1   49  Travel_Frequently          1       Married       No               2   
2   37      Travel_Rarely          2        Single      Yes               4   
3   33  Travel_Frequently          4       Married      Yes               5   
4   27      Travel_Rarely          1       Married       No               7   

   DailyRate  Gender  accepted for the interview  
0       1102  Female                        True  
1        279    Male                       False  
2       1373    Male                       False  
3       1392  Female                       False  
4        591    Male                       False

In [179]:
encoder=OrdinalEncoder()
for colums in df.columns:
  if df[colums].dtype=="object":
    df[colums]=encoder.fit_transform(df[[colums]])
df["accepted for the interview"]=encoder.fit_transform(df[["accepted for the interview"]])
df.head()

Age  BusinessTravel  Education  MaritalStatus  OverTime  EmployeeNumber  \
0   41             2.0          2            2.0       1.0               1   
1   49             1.0          1            1.0       0.0               2   
2   37             2.0          2            2.0       1.0               4   
3   33             1.0          4            1.0       1.0               5   
4   27             2.0          1            1.0       0.0               7   

   DailyRate  Gender  accepted for the interview  
0       1102     0.0                         1.0  
1        279     1.0                         0.0  
2       1373     1.0                         0.0  
3       1392     0.0                         0.0  
4        591     1.0                         0.0

In [180]:
stdsacle=StandardScaler()
for colums in df.columns:
  if df[colums].dtype=="int64":
    df[colums]=stdsacle.fit_transform(df[[colums]])
df.head()

Age  BusinessTravel  Education  MaritalStatus  OverTime  \
0  0.452168             2.0  -0.897027            2.0       1.0   
1  1.331314             1.0  -1.876080            1.0       0.0   
2  0.012595             2.0  -0.897027            2.0       1.0   
3 -0.426978             1.0   1.061078            1.0       1.0   
4 -1.086338             2.0  -1.876080            1.0       0.0   

   EmployeeNumber  DailyRate  Gender  accepted for the interview  
0       -1.710930   0.735781     0.0                         1.0  
1       -1.709278  -1.303018     1.0                         0.0  
2       -1.705975   1.407124     1.0                         0.0  
3       -1.704323   1.454192     0.0                         0.0  
4       -1.701020  -0.530108     1.0                         0.0

In [181]:
matrix = df.corr(numeric_only=True)
fig=px.imshow(matrix,x=matrix.columns,y=matrix.index,color_continuous_scale='RdBu_r',text_auto='.2f',aspect="auto")
fig.update_layout(title='Correlation Matrix',xaxis_showgrid=False,yaxis_showgrid=False,width=1000,height=1000,)
fig.show()

Compare to accepted for the interview , hightest corrolations have BiusinessTravell, Educatin and OverTime

In [182]:
x_train,x_test,y_train,y_test=train_test_split(list(zip(df["BusinessTravel"],df["DailyRate"],df["Education"])),df["accepted for the interview"],test_size=0.2,random_state=42,shuffle=True)
dict_train={"BusinessTravel DailyRate Education":x_train,"accepted for the interview":y_train,"data":"Training"}
dict_test={"BusinessTravel DailyRate Education":x_test,"accepted for the interview":y_test,"data":"Test"}
df_all=pd.concat([pd.DataFrame(dict_train),pd.DataFrame(dict_test)],ignore_index=True)
df_all.head()

BusinessTravel DailyRate Education  \
0   (2.0, -0.2526524429539402, 1.0610777606082311)   
1   (2.0, 0.4087807141567375, 0.08202518248362939)   
2  (2.0, 0.46328082448046376, 0.08202518248362939)   
3   (2.0, -1.0974041529716971, -1.876079973765574)   
4  (2.0, -0.4087209406991562, 0.08202518248362939)   

   accepted for the interview      data  
0                         0.0  Training  
1                         0.0  Training  
2                         0.0  Training  
3                         0.0  Training  
4                         0.0  Training

Logistic regression

In [183]:
log_model=LogisticRegression()
log_model.fit(x_train,y_train)
accuracy = log_model.score(x_test, y_test)
print(f"Model Accuracy: {accuracy}")
predicted = log_model.predict([[33,1000,7]])
print(f"Prediction for input 40: {predicted}")

Model Accuracy: 0.8963210702341137
Prediction for input 40: [1.]


In [184]:
y_pred=log_model.predict(x_test)
confusion_matrix = metrics.confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[268   0]
 [ 31   0]]


KNN

In [185]:
knn_model=KNeighborsClassifier(n_neighbors=3)
knn_model.fit(x_train,y_train)
accuracy=knn_model.score(x_test,y_test)
print(f"Model Accuracy: {accuracy}")
predicted =knn_model.predict([[33,1000,7]])
print(f"Prediction for input 40: {predicted}")

Model Accuracy: 0.8561872909698997
Prediction for input 40: [0.]


In [186]:
y_pred=knn_model.predict(x_test)
confusion_matrix = metrics.confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[251  17]
 [ 26   5]]


Gaussian Naive Bayes

In [187]:
nb_model= GaussianNB()
nb_model.fit(x_train,y_train)
accuracy=nb_model.score(x_test,y_test)
print(f"Model Accuracy: {accuracy}")
predicted =knn_model.predict([[33,1000,77]])
print(f"Prediction for input 40: {predicted}")

Model Accuracy: 0.8963210702341137
Prediction for input 40: [0.]


In [188]:
y_pred=nb_model.predict(x_test)
confusion_matrix = metrics.confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[268   0]
 [ 31   0]]
